apiVersion: argoproj.io/valpha1
kind: Application
metadata:
  name: testkube-tests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zerogravit1/testkube-argocd.git
    targetRevision: HEAD
    path: postman-collections
    plugin:
      name: testkube
  destination:
    server: https://kubernetes.default.svc
    namespace: testkube